<a href="https://colab.research.google.com/github/ByteForge-sg/EDAlab/blob/main/numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

#create 1D array
a=np.array([1,2,3,4,5])

print(a)
print()

#create 2D array
b=np.array([
    [1,2,3],
    [4,5,6],
    [6,7,8]
])

print(b)

[1 2 3 4 5]

[[1 2 3]
 [4 5 6]
 [6 7 8]]


In [10]:
#matrix properties
import numpy as np

a=np.array([
    [2,4,6],
    [8,10,12],
    [67,89,29]
])
b=np.array(["shashwat","ajay","atul"])

print(a.ndim)
print(a.dtype)
print(b.dtype)

2
int64
<U8


In [20]:
#special matrix types
import numpy as np

a=np.zeros([3,3]) #2D ARRAY
print(a)
print()
b=np.eye(3) #identity matrix
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [34]:
#basic operations & statistics
import numpy as np

a=np.array([
    [1,2,3],
    [2,3,4],
    [3,4,5]
])

b=np.array([
    [4,5,6],
    [6,7,8],
    [7,8,9]
])

print(a+b)
print()
print(a*b) #element wise multiplication
print()
print(np.dot(a,b)) #matrix multiplication
print()
#basic stats operations
print(np.mean(a))
print(np.median(a))
print(np.var(a))
print(np.std(a))


[[ 5  7  9]
 [ 8 10 12]
 [10 12 14]]

[[ 4 10 18]
 [12 21 32]
 [21 32 45]]

[[37 43 49]
 [54 63 72]
 [71 83 95]]

3.0
3.0
1.3333333333333333
1.1547005383792515
94.33333333333333


MINI TASK TO END TODAYS PRACTICE

CREATE A STUDENT ANALYSIS BASIC
CALCULATE AVG MAX MEAN MEDIAN OF THE MARKS

In [35]:

import numpy as np

marks=np.array([
[85,90,88],
[70,75,80],
[95,92,96]
])

print(marks)

print(np.mean(marks))
print()
print(np.mean(marks,axis=1))#for each student(row-wise)
print()
print(np.mean(marks,axis=0))#for each subject(column-wise)
print()
print(np.max(marks))
print()
print(np.mean(marks,axis=1))

print()
#max avg of student
print(np.max(np.mean(marks,axis=1)))


[[85 90 88]
 [70 75 80]
 [95 92 96]]
85.66666666666667

[87.66666667 75.         94.33333333]

[83.33333333 85.66666667 88.        ]

96

[87.66666667 75.         94.33333333]

94.33333333333333
